# Generated by Django 3.1.7 on 2021-02-28 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тега')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug для тегов в url')),
                ('active', models.BooleanField(default=False, verbose_name='Активность тега')),
                ('users', models.ManyToManyField(blank=True, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которые попытались создать тег')),
            ],
        ),
    ]
